[package]
name = "soil-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
soil = { version = "0.1.0", path = "../soil" }
soil-vm = { version = "0.1.0", path = "../soil-vm" }
